# Generated by Django 5.0.1 on 2024-01-20 19:46

import restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='images/category/default.png', upload_to=restaurants.models.get_restaurant_image_filepath),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
