# Generated by Django 5.0.1 on 2024-01-21 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_order_cart_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
